[project]
name = "cmpsc105-lab01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Oscar Emilio Zuniga Macias", email = "zunigamacias01@allegheny.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
]

[project.scripts]
cmpsc105-lab01 = "cmpsc105_lab01:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
